BOTTOM = 'bottom'
TOP = 'top'
LEFT = 'left'
RIGHT = 'right'
TEAM_PENALTY = 100
PAYLOAD_PENALTY = 100
MAX_ITER = 10
DRONE_RADIUS = 50
N_ENEMY_TGT = 'nearest_enemies_target'
ACT = 'action'
STAT = 'status'
SELECTED_ENEMY_DRONES = 'my enemy drones'
MOD_HEALS = 'need health'
MOD_LOOSING = 'some how we are loosing'
MOD_WINNING = 'plans are works'
MOD_COLLECT = 'time to get rich'
MOD_DESTROY = 'destroy all humans'
MAX_ATTACK_RADIUS = 600
ATTACK_RANGE_DELTA = .7
ARC_TRACE_CIRCLE_STEP = 30
TURRETS_RAD = 200

MEM_SWARM_TARGET = 'swarm target'
MEM_SWARM_TARGET_POSITION = 'swarm target position'
MEM_CONTEXT = 'context'
MEM_CONTEXT_STR = 'context string'
MEM_ATTACK_POSITION = 'attack position'
MEM_ATTACK_RADIUS = 'attack radius'
MEM_ENEMY_TARGET = 'enemy target'
MEM_TEAM_TO_DESTROY = 'team to destroy'
MEM_AMBUSH_FLAG = 'ambush state'
MEM_ENEMY_COST = 'enemy cost'
MEM_DRONES = 'drones'
MEM_ENEMY = 'enemy'
MEM_SHOOT_FLAG = 'shoot flag'
MEM_SHOOT_TARGET = 'shoot point'
MEM_ADDITIONAL_POSITIONS = 'additional positions'
MEM_ENEMY_STATE_OFFENCIVE = 'offencive'
MEM_ENEMY_STATE_DEFENCIVE = 'defencive'
MEM_ENEMY_STATE_ON_WAIT = 'on wait'
MEM_ENEMY_STATE_COLLECTOR = 'collector'
MEM_OFFENCIVE_DRONES = "offencive drones"
SPEED_COEFFICIENT = 3
TRACE_STEP = 3

